version: "3.9"

services:

  postgres:
    image: postgres:15.7-alpine3.20
    container_name: mail-db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - ~/.docker-conf/postgres/data/:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  broker:
    image: rabbitmq:3.13.2-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    env_file: .env
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_PASS
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  core-ms:
    image: core-ms:1.0.1
    build: core-service
    container_name: core-ms
    restart: on-failure
    env_file: .env
    depends_on:
      - postgres
      - broker
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/$POSTGRES_DB
      - SPRING_RABBITMQ_HOST=broker
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=$RABBITMQ_DEFAULT_USER
      - SPRING_RABBITMQ_PASSWORD=$RABBITMQ_DEFAULT_PASS
    ports:
      - "8081:8081"

  answering-ms:
    image: answering-ms:1.0.1
    build: answering-service
    container_name: answering-ms
    restart: on-failure
    env_file: .env
    depends_on:
      - postgres
      - broker
      - core-ms
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/$POSTGRES_DB
      - SPRING_RABBITMQ_HOST=broker
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=$RABBITMQ_DEFAULT_USER
      - SPRING_RABBITMQ_PASSWORD=$RABBITMQ_DEFAULT_PASS
    ports:
      - "8080:8080"

  mail-ms:
    image: mail-ms:1.0.1
    build: mail-service
    container_name: mail-ms
    restart: on-failure
    env_file: .env
    depends_on:
      - broker
      - core-ms
    environment:
      - SPRING_RABBITMQ_HOST=broker
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=$RABBITMQ_DEFAULT_USER
      - SPRING_RABBITMQ_PASSWORD=$RABBITMQ_DEFAULT_PASS
    ports:
      - "8082:8082"