version: "3.9"

services:

  postgres:
    image: postgres:15.7-alpine3.20
    container_name: mail-db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  answering-ms:
    build: answering-service
    container_name: answering-ms
    restart: on-failure
    env_file: .env
    depends_on:
      - postgres
    environment:
      spring.datasource.url: $SPRING_DATASOURCE_URL
    ports:
      - "8081:8081"