server:
  port: 8083

spring:
  application:
    name: mail-service

  rabbitmq:
    host: localhost
    port: 15672
    username: user
    password: pass

  mail:
    host: smtp.gmail.com
    port: 587
    username: smtp.mail.sender.service@gmail.com
    password: Jopa113!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true