server:
  port: 8082

spring:
  application:
    name: mail-service

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: pass

  mail:
    host: smtp.gmail.com
    port: 587
    username: smtp.mail.sender.service@gmail.com
    password: pdua hxir qsel xjaa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true