server:
  port: 8081

spring:
  application:
    name: answering-service

  datasource:
    url: jdbc:postgresql://localhost:5432/mail
    username: postgres
    password: 1111

  rabbitmq:
    host: localhost
    port: 15672
    username: user
    password: pass

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true