server:
  port: 8081

spring:
  application:
    name: answering-service

  datasource:
    url: jdbc:postgresql://localhost:5432/mail
    username: postgres
    password: 1111
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true